---
name: Regression Tests

on: [push, pull_request]

jobs:
  regression:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        crsversion: [3.3.0, 3.2.0]
        poetry-version: [1.1.13]

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: "Run tests"
        run: |
          curl -L https://github.com/coreruleset/coreruleset/archive/refs/tags/v${{ matrix.crsversion }}.tar.gz -o - | tar xzvf -
          poetry install
          poetry run secrules-parser -c --output-type github -f coreruleset-${{ matrix.crsversion }}/rules/*.conf

